% -------------------------------------------------------------------
%  Generated by MATLAB on 25-Mar-2016 23:41:30
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('sanzhongboxing.mat');

ans = 1;

fid = 3;

i = 4097;

r = saveVarsMat.r; % <1x4096 double> too many elements

t = saveVarsMat.t; % <1x32768 double> too many elements

y = saveVarsMat.y; % <1x4096 double> too many elements

clear saveVarsMat;
